name: publish-docs

on:
  push:
    branches:
    - main

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.14

    - name: Install dependencies
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip
        python -m pip install uv
        uv sync --group docs

    - name: Build the docs
      run: |
        source .venv/bin/activate
        cd docs 
        make html
        cd ..

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
